2019-08-01/portfolio/blog/urls.py
from django.urls import path
import blog.views as views

urlpatterns = [
    path('create', views.PostCreate.as_view()),
    path('list', views.PostList.as_view()),
    path('update/<int:pk>', views.PostUpdate.as_view()),
    path('delete/<int:pk>', views.PostDelete.as_view()),
]

2019-08-01/portfolio/portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name = "home.html")),
    path('blog/', include('blog.urls'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

2019-08-01/portfolio/blog/models.py
from django.db import models

# Create your models here.
class  Post(models.Model):
    title = models.TextField()
    body = models.TextField()

2019-08-01/portfolio/blog/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from blog.models import Post


# Create your views here.
class PostCreate(CreateView):
    model = Post
    fields = ['title', 'body']
    success_url = '/blog/list'


class PostList(ListView):
    model = Post

class PostUpdate(UpdateView):
    model = Post
    fields = ['title', 'body']
    success_url = '/blog/list'


class PostDelete(DeleteView):
    model = Post
    success_url = '/blog/list'

2019-08-01/portfolio/blog/templates/blog/post_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>

2019-08-01/portfolio/blog/templates/blog/post_form.html
{% extends 'home.html' %}
{% block body %}
    <section class="masthead">
        <div class="container">
            <form method="post">{% csrf_token %}
                <div class="form-group">
                    <label for="title">Title</label>
                    <textarea name="title" cols="40" rows="10" required="" id="id_title" class="form-control" >{{ form.title.value|default:"nothing" }}</textarea>
                    <label for="body">Body</label>
                    <textarea name="body" cols="40" rows="10" class="form-control" required="" id="id_body">{{ form.body.value|default:"nothing"}}</textarea>
                    <input class = "form-control" type="submit" value="Save">
                </div>
            </form>
        </div>
    </section>
{% endblock %}

2019-08-01/portfolio/blog/templates/blog/post_list.html
{% extends "home.html" %}
{% load static %}
{% block body %}
  <section class="text-center masthead">
    <div class="container">

    <h1 class="masthead-heading text-uppercase mb-0">Articles</h1>
    <ul>
    {% for article in object_list %}

    <div class="card" style="width: 18rem;">
            <img src="{% static 'img/mountains.jpeg' %}" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title">{{article.title}}</h5>
              <p class="card-text">{{ article.body }}</p>
              <a href="/blog/update/{{article.id}}" class="btn btn-primary">Edit</a>
              <a href="/blog/delete/{{article.id}}" class="btn btn-primary">Delete</a>
            </div>
          </div>
    </div>
    {% empty %}
        <li>No articles yet.</li>
    {% endfor %}
    </ul>
    </div>
  </section>
{% endblock %}